[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/joz/printer_data/comms/klippy.sock
[authorization]
trusted_clients:
    100.72.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FC00::/7
    FE80::/10
    ::1/128
    100.64.0.0/10
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
[octoprint_compat]
[history]
[file_manager]
queue_gcode_uploads: True
enable_object_processing: True
[power Printer]
type: gpio
pin: gpiochip0/gpio4
initial_state: off
restart_klipper_when_powered: True
restart_delay: 3
locked_while_printing: True
on_when_job_queued: True
bound_services: 
	klipper
	crowsnest
[power Heatbed]
type: klipper_device
initial_state: off
locked_while_printing: True
object_name: output_pin heatbed_relay
[power Extruder]
type: klipper_device 
initial_state: off
locked_while_printing: True
object_name: output_pin extruder_relay
[update_manager]
channel: dev
refresh_interval: 168
[job_queue]
load_on_startup: True
[update_manager mainsail]
path: /home/joz/mainsail
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json
[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/joz/mainsail-config
primary_branch: master
type: git_repo
[update_manager Klipper-Adaptive-Meshing-Purging]
primary_branch: main
managed_services: klipper
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging
path: /home/joz/Klipper-Adaptive-Meshing-Purging
channel: dev
type: git_repo
[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
primary_branch: v5
managed_services: crowsnest
system_dependencies: system-dependencies.json
virtualenv: ~/crowsnest-env
requirements: requirements.txt
[spoolman]
server: http://192.168.100.110:7912
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main